sequenceDiagram
    actor dataProvider
    participant Pyth's oracle program
    participant Wormhole
    participant Hermes
    actor priceConsumer
    autonumber
    dataProvider->>Pyth's oracle program:submit pricing information
    Pyth's oracle program-->Pyth's oracle program:combines data and compute price
    Pyth's oracle program->>Wormhole:transfer data via Wormhole
    Hermes->>Wormhole: listen to price update
    priceConsumer->>Hermes:get latest price data
    priceConsumer->>Pyth's oracle program:verify && publish price
